// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasinoApi.Migrations
{
    [DbContext(typeof(CasinoDbContext))]
    [Migration("20251212162016_welcomeBonus")]
    partial class welcomeBonus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasinoApi.CasinoTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserClerkUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserClerkUserId");

                    b.HasIndex("ClerkUserId", "CreatedAt");

                    b.ToTable("CasinoTransactions");
                });

            modelBuilder.Entity("CasinoApi.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserClerkUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("WinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserClerkUserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CasinoApi.User", b =>
                {
                    b.Property<string>("ClerkUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasClaimedWelcomeBonus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClerkUserId");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CasinoApi.CasinoTransaction", b =>
                {
                    b.HasOne("CasinoApi.User", null)
                        .WithMany("CasinoTransactions")
                        .HasForeignKey("UserClerkUserId");
                });

            modelBuilder.Entity("CasinoApi.GameSession", b =>
                {
                    b.HasOne("CasinoApi.User", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("UserClerkUserId");
                });

            modelBuilder.Entity("CasinoApi.User", b =>
                {
                    b.Navigation("CasinoTransactions");

                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
