// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasinoApi.Migrations
{
    [DbContext(typeof(CasinoDbContext))]
    [Migration("20260812135440_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasinoApi.CasinoTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId", "CreatedAt");

                    b.ToTable("CasinoTransactions");
                });

            modelBuilder.Entity("CasinoApi.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WinAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CasinoApi.User", b =>
                {
                    b.Property<string>("ClerkUserId")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("HasClaimedWelcomeBonus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogIn")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClerkUserId");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SlotsResult", b =>
                {
                    b.Property<string>("ClerkUserId")
                        .HasColumnType("text");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<string>("Symbols")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("WinAmount")
                        .HasColumnType("numeric");

                    b.HasKey("ClerkUserId");

                    b.ToTable("SlotsResults");
                });

            modelBuilder.Entity("SlotsSpinRequest", b =>
                {
                    b.Property<string>("ClerkUserId")
                        .HasColumnType("text");

                    b.Property<decimal>("Bet")
                        .HasColumnType("numeric");

                    b.HasKey("ClerkUserId");

                    b.ToTable("SlotsSpinRequests");
                });

            modelBuilder.Entity("CasinoApi.CasinoTransaction", b =>
                {
                    b.HasOne("CasinoApi.User", null)
                        .WithMany("CasinoTransactions")
                        .HasForeignKey("ClerkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CasinoApi.GameSession", b =>
                {
                    b.HasOne("CasinoApi.User", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("ClerkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CasinoApi.User", b =>
                {
                    b.Navigation("CasinoTransactions");

                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
